# -Try to find SuperLU
#
# The following are set after configuration is done: 
#  SUPERLU_FOUND
#  SUPERLU_LIBRARIESBRARIES
#  SUPERLU_INCLUDE_DIR

FIND_PATH(SUPERLU_INCLUDE_DIR slu_Cnames.h

  /usr/include/superlu
  /usr/local/include/superlu
  )

FIND_LIBRARY(SUPERLU_LIBRARIES

  NAMES libsuperlu.a
  PATHS 
  /usr/lib 
  /usr/local/lib
  )

IF (SUPERLU_LIBRARIES AND SUPERLU_INCLUDE_DIR)
  SET(SUPERLU_LIBRARIES ${SUPERLU_LIBRARIES})
  SET(SUPERLU_FOUND "YES")
ELSE (SUPERLU_LIBRARIES AND SUPERLU_INCLUDE_DIR)
  SET(SUPERLU_FOUND "NO")
ENDIF (SUPERLU_LIBRARIES AND SUPERLU_INCLUDE_DIR)

IF (SUPERLU_FOUND)
  MESSAGE(STATUS "Found SUPERLU: ${SUPERLU_LIBRARIES}")
ELSE (SUPERLU_FOUND)
  MESSAGE(FATAL_ERROR "Could not find SUPERLU library")
ENDIF (SUPERLU_FOUND)

MARK_AS_ADVANCED(

  SUPERLU_LIBRARIES
  SUPERLU_INCLUDE_DIR
  )