"""Script generated by PythonScriptDraw2DCurves."""
import numpy as np
import matplotlib.pyplot as plt
x = [0,1,2,3,4,5,6,7,8,9];
y = [-0.329554,0.536459,-0.444451,0.10794,-0.0452059,0.257742,-0.270431,0.0268018,0.904459,0.83239];
plt.plot(x,y);
plt.show()