#ifndef _DRAWCURVES_H_
#define _DRAWCURVES_H_

#include <string>
#include <sstream>
#include <fstream>
#include <assertext.h>
#include <Log.h>
using std::string;
using std::stringstream;

namespace UTILITY{

  /**
   * given a set of points (xi,yi), generate a python script to for drawing this
   * curve, and save it to a file.
   */
  template<class VECTOR>
  class PythonScriptDraw2DCurves{
  
  public:
	static bool write(const string fname,const VECTOR &y,const double dx=1.0,const double x0=0.0f,const string style=""){

	  VECTOR x(y.size());
	  for (int i = 0; i < x.size(); ++i){
		x[i] = x0+i*dx;
	  }
	  return write(fname,y,x,style);
	}
	static bool write(const string fname,const VECTOR &y,const VECTOR &x,const string style=""){
	  return write(fname,defineCurve(y,x,"",style),false);
	}

	bool add(const string name,const VECTOR &y,const double dx=1.0,const double x0=0.0f,const string style=""){

	  VECTOR x(y.size());
	  for (int i = 0; i < x.size(); ++i){
		x[i] = x0+i*dx;
	  }
	  return add(name,y,x,style);
	}
	bool add(const string name,const VECTOR &y,const VECTOR &x,const string style=""){
	  const string curve = defineCurve(y,x,name,style);
	  curvesData = curvesData + "\n" + curve;
	  return (curve.size() > 0);
	}
	bool write(const string fname)const{
	  return write(fname,curvesData);
	}
	void clear(){
	  curvesData.clear();
	}

  protected:
	static string head(){
	  const string line1("\"\"\"Script generated by PythonScriptDraw2DCurves.\"\"\"\n");
	  const string line2("import numpy as np\n");
	  const string line3("import matplotlib.pyplot as plt\n");
	  return line1+line2+line3;
	}
	static string end(bool useLabel){
	  return useLabel?(string("plt.legend()\nplt.show()")):string("plt.show()");
	}
	static string defineCurve(const VECTOR &y,const VECTOR &x,const string name="",const string style=""){

	  assert_eq(x.size(),y.size());
	  if(y.size() <= 0){
		ERROR_LOG("the input data is zero");
		return string("");
	  }

	  stringstream script;
	  const string xName = name+"_x";
	  const string yName = name+"_y";
	  const string labelCmd = string(",label=\'")+name+"\'";
	  const string styleCmd = style.size()>0?(string(",\'")+style+string("\'")):(string(""));
	  script<< xName << " = [" << x[0];
	  for (int i = 1; i < x.size(); ++i){
		script << "," << x[i];
	  }
	  script << "];\n";

	  script << yName << " = [" << y[0];
	  for (int i = 1; i < y.size(); ++i){
		script << "," << y[i];
	  }
	  script << "];\n";
	  script << "plt.plot("<<xName<<","<<yName<<styleCmd<<labelCmd<<");\n";
	  return script.str();
	}
	static bool write(const string fname, const string curves,bool useLabel=true){

	  const string script = head()+string("\n")+curves+end(useLabel);
	  std::ofstream file;
	  file.open(fname.c_str());
	  ERROR_LOG_COND("failed to open file for writing: "<<fname,file.is_open());
	  file << script;
	  const bool succ = file.is_open();
	  file.close();
	  return succ;
	}

  private:
	string curvesData;
  };
}
#endif /* _DRAWCURVES_H_ */
